config/routes.rb
MissileServer::Application.routes.draw do
  resources :comments

  resources :missiles do
    collection do
      get :by_ids ,to: :missiles_by_id
      get :new_missiles
      get :hot_missile
      get 'search/:key' ,to: :search
    end
  end
  resources :tags, only: [:index, :show]
  root 'missiles#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :missile, :body, presence: true
  belongs_to :missile
end

app/models/missile.rb
class Missile < ActiveRecord::Base
  validates :message, presence: true
  has_and_belongs_to_many :tags
  after_create :prepare_tags
  has_many :comments

  def self.search(key)
    return scoped unless key.present?
    where(['title LIKE ? OR message LIKE ?', "%#{key}%", "%#{key}%"])
  end

  private

  def prepare_tags
    tag_strings=self.message.scan /#[^\s]+/
    tags=[]
    tag_strings.each do |tag_string|
      tag_string = tag_string[1..tag_string.length]
      tag = Tag.find_by_name tag_string
      tag = Tag.create name: tag_string unless tag
      tags <<  tag
    end
    self.tags << tags
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :missiles
  validates :name, presence: true
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :verified_request?

  private
  def verified_request?
    if request.content_type == "application/json"
      true
    else
      super()
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    if params[:missile_id].present?
      missile = Missile.find_by_id(params[:missile_id])
      if missile
        @comments = missile.comments
      else
        @comments = nil
      end
    end
    @comments = [] if @comments.nil?
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:missile_id, :body)
    end
end

app/controllers/missiles_controller.rb
class MissilesController < ApplicationController
  before_action :set_missile, only: [:show, :edit, :update, :destroy]

  # GET /missiles
  # GET /missiles.json
  def index
    @missiles = Missile.order("created_at desc").page params[:page]
  end

  def new_missiles
    @missiles = Missile.where("id > ?", params[:id].present? ? params[:id] : 0).page params[:page]
    render 'index'
  end

  def hot_missile
    @missile = Missile.first(offset: rand(Missile.count))
    render 'show'
  end

  def search
    @missiles = Missile.search(params[:key]).page params[:page]
    render 'index'
  end

  def missiles_by_id
    respond_to do |format|
      if params[:ids].present?
        not_found = []
        found = []
        ids = params[:ids].split(",")
        ids.each do |id|
          missile = Missile.find_by_id(id)
          if missile
            found << missile
          else
            not_found << id.to_i
          end
        end
        format.html {
          @missiles = found #issue : undefined method `current_page' for #<Array:0x007f6a0c493900>
          render action: 'index'
        }
        format.json { render json: {missiles: found, not_found: not_found}, status: :ok }
      else
        format.html {
          @missiles = [] #issue : undefined method `current_page' for []:Array
          render action: 'index'
        }
        format.json { render json: {errors: ["Required params missing."]}, status: :not_acceptable }
      end
    end
  end

  # GET /missiles/1
  # GET /missiles/1.json
  def show
  end

  # GET /missiles/new
  def new
    @missile = Missile.new
  end

  # GET /missiles/1/edit
  def edit
  end

  # POST /missiles
  # POST /missiles.json
  def create
    @missile = Missile.new(missile_params)

    respond_to do |format|
      if @missile.save
        format.html { redirect_to @missile, notice: 'Missile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @missile }
      else
        format.html { render action: 'new' }
        format.json { render json: @missile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missiles/1
  # PATCH/PUT /missiles/1.json
  def update
    respond_to do |format|
      if @missile.update(missile_params)
        format.html { redirect_to @missile, notice: 'Missile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @missile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missiles/1
  # DELETE /missiles/1.json
  def destroy
    @missile.destroy
    respond_to do |format|
      format.html { redirect_to missiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_missile
      @missile = Missile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def missile_params
      params.require(:missile).permit(:title, :message)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show]
  respond_to :json

  # GET /tags.json
  def index
    respond_with Tag.page(params[:page]).map(&:name)
  end

  # GET /tags/1.json
  def show
    respond_with @tag ? @tag.missiles.page(params[:page]) : []
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find_by_name(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:missile_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/missiles_helper.rb
module MissilesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :missile_id %><br>
    <%= f.text_field :missile_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Missile</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.missile %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Missile:</strong>
  <%= @comment.missile %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Missile Server</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/missiles/_form.html.erb
<%= form_for(@missile) do |f| %>
  <% if @missile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@missile.errors.count, "error") %> prohibited this missile from being saved:</h2>

      <ul>
      <% @missile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/missiles/edit.html.erb
<h1>Editing missile</h1>

<%= render 'form' %>

<%= link_to 'Show', @missile %> |
<%= link_to 'Back', missiles_path %>

app/views/missiles/index.html.erb
<h1>Listing missiles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @missiles.each do |missile| %>
      <tr>
        <td><%= missile.title %></td>
        <td><%= missile.message %></td>
        <td><%= link_to 'Show', missile %></td>
        <td><%= link_to 'Edit', edit_missile_path(missile) %></td>
        <td><%= link_to 'Destroy', missile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @missiles %>

<br>

<%= link_to 'New Missile', new_missile_path %>

app/views/missiles/new.html.erb
<h1>New missile</h1>

<%= render 'form' %>

<%= link_to 'Back', missiles_path %>

app/views/missiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @missile.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @missile.message %>
</p>

<%= link_to 'Edit', edit_missile_path(@missile) %> |
<%= link_to 'Back', missiles_path %>